/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LogRouteImport } from './routes/log'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankRouteImport } from './routes/rank'
import { Route as TrainRouteImport } from './routes/train'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FriendsCodeRouteImport } from './routes/friends.$code'
import { Route as GuideIdRouteImport } from './routes/guide.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsCodeRoute = FriendsCodeRouteImport.update({
  id: '/friends/$code',
  path: '/friends/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideIdRoute = GuideIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GuideRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rank': typeof RankRoute
  '/train': typeof TrainRoute
  '/friends': typeof FriendsRoute
  '/friends/$code': typeof FriendsCodeRoute
  '/guide/$id': typeof GuideIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rank': typeof RankRoute
  '/train': typeof TrainRoute
  '/friends': typeof FriendsRoute
  '/friends/$code': typeof FriendsCodeRoute
  '/guide/$id': typeof GuideIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRouteWithChildren
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rank': typeof RankRoute
  '/train': typeof TrainRoute
  '/friends': typeof FriendsRoute
  '/friends/$code': typeof FriendsCodeRoute
  '/guide/$id': typeof GuideIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/log'
    | '/login'
    | '/profile'
    | '/rank'
    | '/train'
    | '/friends'
    | '/friends/$code'
    | '/guide/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/log'
    | '/login'
    | '/profile'
    | '/rank'
    | '/train'
    | '/friends'
    | '/friends/$code'
    | '/guide/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/log'
    | '/login'
    | '/profile'
    | '/rank'
    | '/train'
    | '/friends'
    | '/friends/$code'
    | '/guide/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRouteWithChildren
  LogRoute: typeof LogRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RankRoute: typeof RankRoute
  TrainRoute: typeof TrainRoute
  FriendsRoute: typeof FriendsRoute
  FriendsCodeRoute: typeof FriendsCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$code': {
      id: '/friends/$code'
      path: '/friends/$code'
      fullPath: '/friends/$code'
      preLoaderRoute: typeof FriendsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$id': {
      id: '/guide/$id'
      path: '/$id'
      fullPath: '/guide/$id'
      preLoaderRoute: typeof GuideIdRouteImport
      parentRoute: typeof GuideRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuideRouteChildren {
  GuideIdRoute: typeof GuideIdRoute
}

const GuideRouteChildren: GuideRouteChildren = {
  GuideIdRoute: GuideIdRoute,
}

const GuideRouteWithChildren = GuideRoute._addFileChildren(GuideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRouteWithChildren,
  LogRoute: LogRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RankRoute: RankRoute,
  TrainRoute: TrainRoute,
  FriendsRoute: FriendsRoute,
  FriendsCodeRoute: FriendsCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
